apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: reflector
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: reflector
      version: 9.1.45
      sourceRef:
        kind: HelmRepository
        name: emberstack
        namespace: flux-system
  install:
  values:
    replicaCount: 1
    image:
      pullPolicy: IfNotPresent

    # Default reflector behavior
    configuration:
      clusterDomain: cluster.local
      enableCredentialsSync: true
      enableTLS: true
