apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email:
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers: cloudeflare-email
    key: email
    - dns01:
        cloudflare:
          apiTokenSecretRef:
            name: cloudflare-secret
            key: api-token
