apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-local-ckcjsellers
  namespace: cert-manager
  annotations:
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
spec:
  secretName: wildcard-tls
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  dnsNames:
  - local.ckcjsellers.com
  - "*.local.ckcjsellers.com"
